### ISSUE TITLE
CongratsPerLevel.Enable = 0 (Not working)

### ISSUE THREAD

**Issue by NeboUA** [azerothcore/mod-congrats-on-level#25]
Updating **mod_congratsonlevel.conf**, set:
```
# Enable the Per level congratulations announcement (1: true | 0: false)
CongratsPerLevel.Enable = 0
```
both set to 0
(Not working)
Still receiving global announcements.

AzerothCore rev. 5cae59e3943b+ 2023-07-09 16:51:30 +0000 (master branch) (Unix, RelWithDebInfo, Static)

Ubuntu 22.04.2 LTS

**Comment by pangolp** [comment]
Basically, what you want to get out is the chat message when the player starts on the server? I will check it out.

However, I'm wondering... why do people get annoyed by that kind of message? I have 6 modules and for example, it doesn't bother me when people log in to the server to see what modules the server has active.

It is not an attack, it is simply a question. I would like to know. Unless, you want to hide the message because you temporarily disable the module and it is clear that you do not want the message to appear, if the module is disabled, because it generates configuration in people.

**Comment by pangolp** [comment]
With the latest version of the emulator, if I set a 0, the message does not appear in the chat.

```
# Enable the module? (1: true | 0: false)

Congrats.Enable = 0

# Enable the Per level congratulations announcement (1: true | 0: false)
CongratsPerLevel.Enable = 1

# Announce the module when the player logs in?

Congrats.Announce = 0
```

![WoWScrnShot_071223_031123](https://github.com/azerothcore/mod-congrats-on-level/assets/2810187/cae6113f-a80b-4fbd-afe5-1f24b4c13e70)

Then, I changed the 0 to a 1. And the message appeared.
So I can't understand what you mention.
I need more information to understand.

![WoWScrnShot_071223_031531](https://github.com/azerothcore/mod-congrats-on-level/assets/2810187/8047827c-d5b9-4407-a995-3f132f967ebb)

If you can accompany it, screenshots or a video (no need to talk) but maybe that way I can explain it better. Because so far, I do not understand what would be the fault.

**Comment by NeboUA** [comment]
I wanted to disable worldwide announcement when player reaches 10,20,30... etc. level. Because when server have online 100+ there are too much of these messages.
I totally don't mind to leave credits for the mod on login.

Thank you for the response, I'll test is asap and reply how it goes.

**Comment by pangolp** [comment]
The point is that you disable all messages. You have no way to activate some of them and not others. The module activates all or none of them. There is no way to activate only certain messages, it does not currently work that way.

**Comment by NeboUA** [comment]
**I can't** disable all messages, it doesn't work. That's what I'm trying to say

`# Enable the module? (1: true | 0: false)

Congrats.Enable = 1

# Enable the Per level congratulations announcement (1: true | 0: false)
CongratsPerLevel.Enable = 0

# Announce the module when the player logs in?

Congrats.Announce = 0
`
Still receiving these messages:
![253833784-e0a97ae6-3994-4280-9b6e-5dddb843dcbd](https://github.com/azerothcore/mod-congrats-on-level/assets/48227326/3538b77e-e410-4723-ab93-afcdac40fd99)

**Comment by pangolp** [comment]
That should not happen, in the code, there is nothing that does that, in case they are deactivated. Did you check what I put above?

**Comment by NeboUA** [comment]
Yes I've checked, I'm fine with disabling all messages if it will disable CongratsPerLevel announce.

I also have these mods installed:

- [mod-globalchat](https://github.com/Gozzim/mod-globalchat)
- duelreset
- [mod-transmog](https://github.com/azerothcore/mod-transmog)

maybe there is interaction with mod-globalchat. Сonjecture.

**Comment by pangolp** [comment]
Unknown. I would have to do some tests to see.
I did disable the messages, but I didn't try leveling up to level 10 and stuff.
I just turned them off.
Maybe I'm wrong, and it really is failing.
I'll see if I can do some tests later.

**Comment by pangolp** [comment]
Please review the changes, set the value to 0 and let me know if it works. At least it worked for me, but you can't do it with the server running. In my case, I had to log out and log back in. Please note that I moved the awards to the database, so you will have to do some testing before putting it on a production server.

**Comment by NeboUA** [comment]
Alright, I've made a new build and tested it. All works perfectly now. Thank you very much.

**Comment by pangolp** [comment]
> Alright, I've made a new build and tested it. All works perfectly now. Thank you very much.

You are welcome.
